### ISSUE TITLE
Add docs site

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/eslint-plugin-gridsome#48]
docs site with [vuepress](https://vuepress.vuejs.org/).
See: https://kazupon.github.io/eslint-plugin-vue-i18n/

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Hey hanci!!
I want to create eslint-plugin-gridsome's docs site with Vuepress and Netlify.
This is PR: https://github.com/gridsome/eslint-plugin-gridsome/pull/51.
So, can you set Netlify's deploy setting?
Build Command: `npm run docs:build`
Publish directory: `docs/.vuepress/dist`

**Comment by tyankatsu0105** [comment]
You can decide the domain name.
But, maybe it looks like this? `https://eslint.gridsome.org/`

**Comment by hjvedvik** [comment]
That would be great @tyankatsu0105 :) I can take a look at it on Monday (or earlier if I can). Tommy and me are in New Zealand atm and will be offline for a few days.

**Comment by tyankatsu0105** [comment]
Great! Enjoy your trip :)

**Comment by hjvedvik** [comment]
@tyankatsu0105 The site is available at https://eslint.gridsome.org/ now :) Really great work!! Its currently building from the `feat/48-document-site` branch, but I can switch it when its merged.

**Comment by tyankatsu0105** [comment]
@hjvedvik 
Thanks!!
PR is merged.
Please switch branch :)

**Comment by hjvedvik** [comment]
@tyankatsu0105 Done :)

**Comment by tyankatsu0105** [comment]
Thank you!
