### ISSUE TITLE
Upgrade Node.js version

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/eslint-plugin-gridsome#49]
- engines in `package.json`

**Comment by Chaitanya1010** [comment]
I would like to work on this, and would like to know what engine version is best suitable?

**Comment by tyankatsu0105** [comment]
@Chaitanya1010
Awesome!!
Maybe we should upgrade than v8.
Because v8.x.x is EoL soon.
See: https://nodejs.org/en/about/releases/

So we should upgrade v10.13.0!!
