### ISSUE TITLE
Welcome contributor hacknug🎉

### ISSUE THREAD

**Issue by tyankatsu0105** [gridsome/eslint-plugin-gridsome#53]
@hacknug 
Thanks you for your advice and report issue all the time.
So, I want to add you to the contributors list in README.md.
How about you?
If you mind, run this script and create PR:
```bash
npx all-contributors add hacknug .....
```
You can check usage more https://allcontributors.org/docs/ja/cli/usage#all-contributors-add

**Comment by hacknug** [comment]
Thanks! Just opened the PR with the changes ✌️ ✨
